version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command:
      [
        "start",
        "--auto-build",
        "--http-enabled=true",
        "--hostname-strict=false",
      ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: YOUR_KEYCLOAK_ADMIN_PASSWORD # Change this
      KC_PROXY: edge # If behind a proxy (e.g., Nginx)
    ports:
      - "9000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
